# Generated by Django 2.0 on 2018-03-22 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='employee code')),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'EPM Users Auth',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Disabilities',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_first_login', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.IntegerField(blank=True, choices=[(1, 'Ms'), (2, 'Miss'), (3, 'Mrs'), (4, 'Mr'), (5, 'Prof'), (6, 'Dr'), (7, 'Rev')], null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male')], null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_status', models.IntegerField(choices=[(1, 'Disabled'), (2, 'Not Disabled')], default=2)),
                ('race', models.IntegerField(choices=[(1, 'Asian'), (2, 'Black'), (3, 'Coloured'), (4, 'White')], default=2)),
                ('emp_status', models.IntegerField(choices=[(1, 'Acting'), (2, 'Contract'), (3, 'Fixed - Term'), (4, 'Permanent'), (5, 'Internship'), (6, 'Secondmen'), (7, 'Probationary')], default=4)),
                ('salary_level', models.IntegerField(blank=True, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Branch')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Component')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'verbose_name_plural': 'Employee Profile',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryNotch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_time', models.FloatField(blank=True, null=True)),
                ('part_time', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, choices=[(1, '6/8th'), (2, '5/8th'), (3, '3/8th')], null=True)),
                ('notch', models.IntegerField(blank=True, choices=[(1, 'Full-time notch'), (2, 'Part-time notch')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_supervisor', to='accounts.Employee')),
                ('employees', models.ManyToManyField(related_name='supervisor_staff', to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(blank=True, null=True)),
                ('token_is_used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_notch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.SalaryNotch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disability',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='epmuser',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Token'),
        ),
    ]
